name: "Build"
description: "Executes a compilation."

runs:
  using: "composite"
  steps:
    - name: Compile
      shell: bash
      run: |
        echo "Creating virtual environment"
        python3 -m venv venv
        source venv/bin/activate
        
        sudo apt update
        sudo apt install libmicrohttpd-dev
        cd $(pwd)/monitor_prometheus/lib/prom-client-c/prom
        mkdir build
        cd build
        cmake ..
        make
        sudo make install

        cd ..
        cd ..

        cd promhttp
        mkdir build
        cd build
        cmake ..
        make
        sudo make install

        cd ..
        cd ..
        cd ..
        cd ..

        mkdir build

    - name: Install Conan dependencies
      shell: bash
      run: |
        conan profile detect
        conan install . --build=missing --settings=build_type=Debug
        conan install . --output-folder=build --build=missing --settings=build_type=Debug
        
    - name: Create and build using CMake
      shell: bash
      run: |
        echo "Running cmake with coverage enabled"
        SRC_FOLDER=$(pwd)/src
        cd build
        cmake .. -DCMAKE_TOOLCHAIN_FILE=build/Debug/generators/conan_toolchain.cmake -DCMAKE_BUILD_TYPE=Debug -DRUN_COVERAGE=1
        make -j2